### ISSUE TITLE
v1.4.0 is not available on Maven central repository

### ISSUE THREAD

**Issue by carbonrider** [revdotcom/revai-java-sdk#34]
***Not a bug in SDK***

This is to inform you that v1.4.0 is not available in Maven central repository. I could only see version upto v1.3.0.
This is must for our project to use machine_v2 transcriber.

**Comment by amikofalvy** [comment]
Maven Central Repository website can take anywhere from a few hours to a few days to index new package versions. The v1.4.0 was available right away if requested directly or defined in your pom.xml file, but it took a few hours for it to show up on the maven central site.

You can view the maven repository site here:
https://mvnrepository.com/artifact/ai.rev.speechtotext/revai-java-sdk-speechtotext

**Comment by carbonrider** [comment]
@amikofalvy I had a separate follow up with your sales teams. It was definitely not hours and not few days but took more than 27 days to reflect. Anyways the problem is resolved now. I tried requesting it directly using pom.xml and it didn't work back then.

![image](https://user-images.githubusercontent.com/5756215/159110059-08bdd807-01b3-47a6-9586-658c6248f6de.png)

**Comment by amikofalvy** [comment]
Your screenshot shows something different than what I see. The 1.4.0 version was published to Maven on Feb 28th, the same day the package was released on Github. [Click here to see publish date on maven.](https://search.maven.org/artifact/ai.rev.speechtotext/revai-java-sdk-speechtotext)
<img width="1396" alt="Screen Shot 2022-03-21 at 12 35 15 PM" src="https://user-images.githubusercontent.com/5668128/159350623-1e6a92b0-30c1-476e-aad6-88077f4630a2.png">
<img width="1558" alt="Screen Shot 2022-03-21 at 12 36 16 PM" src="https://user-images.githubusercontent.com/5668128/159350627-a2567f66-a952-4c21-8fa4-46cc319dc339.png">

If you take a look through the issue history for the Sonatype/Maven package publishing you can see how there are occasional delays related to indexing or underlying bugs in the Maven system: https://issues.sonatype.org/browse/MVNCENTRAL-1440?focusedCommentId=386626&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-386626

These slight delays are realities of using these package manager solutions, but as you can see they are usually short delays and usually they won't effect automated build setups as referenced by the SonaType issue linked above:

> Even though you can't browse for them directly on repo1.maven.org yet, Maven and other build tools will be able to resolve them and use them as dependencies.

**Comment by carbonrider** [comment]
My first go to site for Maven packages is always mvnrepository.com, so I couldn't see it there and the maven CLI was not able to resolve the dependency (Though I could see it on Github). Hence we had to have a call with the sales team. Not sure, where was the problem. Anyways, its working now.
